version: '3.8'

services:
  # Layanan Backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    environment:
      # Variabel disesuaikan untuk terhubung ke kontainer yang SUDAH ADA
      # Gunakan nama kontainer yang sedang berjalan: 'neo4j-v5-3' dan 'ollama'
      - NEO4J_URI=bolt://neo4j-v5-3:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=12345678 # Ganti dengan password Neo4j Anda yang sebenarnya
      - OLLAMA_HOST=http://ollama:11434
      - GROQ_API_KEY= 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 # Praktik terbaik: gunakan variabel dari environment host
    networks:
      - chatbot-net # Bergabung ke jaringan yang sama dengan kontainer lain
    restart: unless-stopped

  # Layanan Frontend Streamlit
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: chatbot-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - chatbot-net
    depends_on:
      - backend
    restart: unless-stopped

networks:
  chatbot-net:
    external: true
